# File: auth_service/Dockerfile

FROM node:lts-alpine
# Set the working directory inside the container
WORKDIR /usr/src/app
COPY package-lock.json .
COPY package.json .
COPY server.js .
RUN npm install --production
 

EXPOSE 8070
CMD [ "npm", "start" ]

